### ISSUE TITLE
set_tcp urscript command does not quite work on ur10e

### ISSUE THREAD

**Issue by vv1122vv** [plusone-robotics/ur_modern_driver#7]
When I send a set_tcp command to UR10e using the add e series support branch to set the tool length to 57cm, and then query it via "rosrun tf tf_echo /tool0 /tool0_controller" I get 53cm. 

It is a brand new UR10e robot.

The command I send via the URScript topic is "set_tcp(p[0,0,0.57,0,0,0])"
On UR10 we had no issues with this.

**Comment by gavanderhoorn** [comment]
Cross-posted to ROS Answers: [Problems setting and verifying TCP for UR10e robots](https://answers.ros.org/question/342583).

**Comment by 130s** [comment]
Closing as this ticket is stale, and as noted in the referenced thread, this package is deprecated.
